language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
      # disable xdebug for performance reasons when code coverage is not needed
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

# It should be generated for each repository
# See https://github.com/yiisoft/yii-dev-tool/issues/14#issuecomment-561390952
notifications:
  slack:
    -
      rooms:
        -
          secure: Qvx4x+h+s8HpOJRYElH5AG3csNFIsqUCcI8KTTflpP+LNDc6R4zhnV2538TrXNM4yZUT8e16x9wqurDs2/MNJOjgAUDhVlV9N2V/yDYEqyw3mvGr9MNIzDxRLlfpJugONhkO4+TL1go8FnBrXwCDpTvLxBo4HusbcSQYQxa6XtP6/KSfFmXh3feydRE95NKEUCJgIU9BPw9Mif99FrYBQGofsa78dR89tW55rfdNrz3daVOnH1iOyU7t+J9sx8JBklKOPawmKGttahbUxuChagiMdC8Onu1kEigo1FGKrif6o0Us2PXFoWvbMLhW4zgvKwSiCozB0FVIKRTBSM5VFGhRHxHaL3v82gicTxdfNyAG5TVAwgpoQoVQt6U27oFNU5LIpnqLM5mK4kDX/IExw/EtuQHZCNhXcM41PU0NJoBgLDyn0/dsPZsVSsQ5cwFvTkzMzXggHxnT2Zbh/HvbZiUfhGIf1FUrmd8XbBBsH2A7/Vt2FaC9EUTKQU5ii6/D84tgp2c0qvp7DjtDd9rrzXDpEdFdYqDcGmbFu5zr6hw2z6LFizIGmrkMNgJVaN1CH/R1Islps0Nm23dLZewjgHNIboR97duZrgCt3gBOx/gzl9tA8iL8kRMT9TU3WnD7Kv49mvyfsfVSVDds5nyle+FzVDxzj6g2g/Kq3AQBMPQ=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: L9bTpHxLU5go+gBbAMdvyF0HZYij7G9ifn+JOtvPFkMavi5xl81d3QdWD6nc/67WSrhgdYJ8ApAwrisvAAyaNYwFBP1VC0BkwVcCXOQLpQKuS+hMankQNHauk3bdfclBU6UTLA8o6Yil7nF+NaUb/j3ElVwjHgiE5IQrHpPOWt3B9VeEFw64LX/oEfoRYYNbkMXMehRkKeWmgthLQ5MR+9KCutUVAWZlKuVFYoTyiXdYq6uk17V42/9XmPuVShY4VTdPfxUAQyXn16+usMfD2K5a75cAGKSSCgqgnDd5OzHh2D2JW6HyFl1RWAVcOrzUda+CUfQQPZbJFRg40m6Rf12YQMri4uszdSlyNEYXwRgxT7MvxNCOX/uwWyIb2D0d1qYs85qkkBIFrS7DBkx57GX3cNQnxUp2+ARvZnmsHlA10csJP0mq6jaJzPAR1mJuh9z26x9LEZ4fki07Rr1W1nvjwvizMDudBRhp3F+rzlWeq2/bX52twJ4pJhYFT6wLI5xjdufgyu9+tjCHPenN0EqeFMpaKxxBuKjfBRAgNZfeh6WP7FA/PurgHh4JvVGj6eDBqU5ZsE5ZguqZ9IzDHbL4EoFOrmzjiXmJkD0ZYIFlwhL841QILTn7R6A708N6ShAuWcJPyrnuPSWABs9sX3xVDXHDZI2OsYge3A5dI6U=
      on_success: never
      on_failure: always
      on_pull_requests: false
